{
  "name": "boxmotors-api",
  "version": "1.0.0",
  "description": "API Backend - THE BOX CONTROL",
  "main": "src/server.js",
  "scripts": {
    "start": "node src/server.js",
    "dev": "nodemon src/server.js"
  },
  "engines": {
    "node": "18.x"
  }
}
